server:
  port: 18082
spring:
  redis:
    host: 192.168.136.160
    port: 6379
  data:
    mongodb:
      uri: mongodb://192.168.136.160:27017/tanhua
  application:
    name: tanhua-dubbo-mongo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848


logging:
  level:
    com.zhouhao: debug
  pattern:
    dateformat: HH:mm:ss:SSS
dubbo:
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: spring-cloud://localhost
    timeout: 10000
  scan:
    base-packages: com.zhouhao.apiImpl  #dubbo中包扫描
